# Generated by Django 5.2.8 on 2025-11-10 06:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('article_code', models.CharField(help_text='Unique product identifier (e.g., ART-034)', max_length=50, unique=True, verbose_name='Article Code')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('category', models.CharField(choices=[('mens', "Men's Clothing"), ('womens', "Women's Clothing"), ('kids', "Kids' Clothing"), ('accessories', 'Accessories'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional product information in JSON format', verbose_name='Additional Metadata')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['article_code'],
                'indexes': [models.Index(fields=['article_code'], name='products_article_b8e540_idx'), models.Index(fields=['category'], name='products_categor_fce6e6_idx'), models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Standard price per unit in UZS', max_digits=10, verbose_name='Base Price')),
                ('premium_price', models.DecimalField(blank=True, decimal_places=2, help_text='Premium/rush price per unit in UZS', max_digits=10, null=True, verbose_name='Premium Price')),
                ('price_type', models.CharField(choices=[('base', 'Base Price'), ('premium', 'Premium Price')], default='base', max_length=10, verbose_name='Default Price Type')),
                ('estimated_minutes', models.IntegerField(default=0, help_text='Estimated time to complete this task (in minutes)', verbose_name='Estimated Minutes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Additional Metadata')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tasks', to='products.product', verbose_name='Product')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tasks', to='tasks.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Product Task',
                'verbose_name_plural': 'Product Tasks',
                'db_table': 'product_tasks',
                'ordering': ['product', 'task'],
                'indexes': [models.Index(fields=['product', 'task'], name='product_tas_product_2a5971_idx')],
                'unique_together': {('product', 'task')},
            },
        ),
    ]
