# Generated by Django 5.2.8 on 2025-11-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tasks', to='tasks.task', verbose_name='Task'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant'], name='products_tenant__8bba44_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['article_code'], name='products_article_b8e540_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_fce6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_active'], name='products_tenant__76cb13_idx'),
        ),
        migrations.AddIndex(
            model_name='producttask',
            index=models.Index(fields=['product', 'task'], name='product_tas_product_2a5971_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='producttask',
            unique_together={('product', 'task')},
        ),
    ]
