# Generated by Django 5.2.8 on 2025-11-10 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(help_text='Unique task identifier (e.g., TASK-001)', max_length=50, unique=True, verbose_name='Task Code')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Name (Uzbek)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Name (Russian)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('cutting', 'Cutting'), ('sewing', 'Sewing'), ('ironing', 'Ironing'), ('packaging', 'Packaging'), ('quality_check', 'Quality Check'), ('other', 'Other')], default='sewing', max_length=20, verbose_name='Category')),
                ('sequence_order', models.IntegerField(default=0, help_text='Order in which this task is typically performed', verbose_name='Sequence Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('tenant', models.ForeignKey(help_text='Workshop this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['sequence_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantity', models.PositiveIntegerField(help_text='Number of units completed', verbose_name='Quantity')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit in UZS', max_digits=10, verbose_name='Price Per Unit')),
                ('total_payment', models.DecimalField(decimal_places=2, help_text='Calculated: quantity * price_per_unit', max_digits=12, verbose_name='Total Payment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20, verbose_name='Status')),
                ('work_date', models.DateField(help_text='Date when work was performed', verbose_name='Work Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_records', to='employees.employee', verbose_name='Approved By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='employees.employee', verbose_name='Employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='products.product', verbose_name='Product')),
                ('product_task', models.ForeignKey(blank=True, help_text='Link to ProductTask for price lookup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_records', to='products.producttask', verbose_name='Product Task Link')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='tasks.task', verbose_name='Task')),
                ('tenant', models.ForeignKey(help_text='Workshop this work record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Work Record',
                'verbose_name_plural': 'Work Records',
                'db_table': 'work_records',
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant'], name='tasks_tenant__9a0aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['code'], name='tasks_code_472c66_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category'], name='tasks_categor_aecfa3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_active'], name='tasks_is_acti_b6e770_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'is_active'], name='tasks_tenant__b92c58_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['tenant'], name='work_record_tenant__631c03_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['employee', 'work_date'], name='work_record_employe_c8bd98_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['status'], name='work_record_status_767f67_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['work_date'], name='work_record_work_da_6a216a_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['product', 'task'], name='work_record_product_fc83e8_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['tenant', 'status'], name='work_record_tenant__c95c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['tenant', 'work_date'], name='work_record_tenant__1bbaed_idx'),
        ),
    ]
