# Generated by Django 5.2.8 on 2025-11-10 06:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(help_text='Unique task identifier (e.g., TASK-001)', max_length=50, unique=True, verbose_name='Task Code')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Name (Uzbek)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Name (Russian)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('cutting', 'Cutting'), ('sewing', 'Sewing'), ('ironing', 'Ironing'), ('packaging', 'Packaging'), ('quality_check', 'Quality Check'), ('other', 'Other')], default='sewing', max_length=20, verbose_name='Category')),
                ('sequence_order', models.IntegerField(default=0, help_text='Order in which this task is typically performed', verbose_name='Sequence Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['sequence_order', 'code'],
                'indexes': [models.Index(fields=['code'], name='tasks_code_472c66_idx'), models.Index(fields=['category'], name='tasks_categor_aecfa3_idx'), models.Index(fields=['is_active'], name='tasks_is_acti_b6e770_idx')],
            },
        ),
    ]
