# Generated by Django 5.2.8 on 2025-11-10 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('products', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantity', models.PositiveIntegerField(help_text='Number of units completed', verbose_name='Quantity')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit in UZS', max_digits=10, verbose_name='Price Per Unit')),
                ('total_payment', models.DecimalField(decimal_places=2, help_text='Calculated: quantity * price_per_unit', max_digits=12, verbose_name='Total Payment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20, verbose_name='Status')),
                ('work_date', models.DateField(help_text='Date when work was performed', verbose_name='Work Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_records', to='employees.employee', verbose_name='Approved By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='employees.employee', verbose_name='Employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='products.product', verbose_name='Product')),
                ('product_task', models.ForeignKey(blank=True, help_text='Link to ProductTask for price lookup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_records', to='products.producttask', verbose_name='Product Task Link')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='tasks.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Work Record',
                'verbose_name_plural': 'Work Records',
                'db_table': 'work_records',
                'ordering': ['-work_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'work_date'], name='work_record_employe_c8bd98_idx'), models.Index(fields=['status'], name='work_record_status_767f67_idx'), models.Index(fields=['work_date'], name='work_record_work_da_6a216a_idx'), models.Index(fields=['product', 'task'], name='work_record_product_fc83e8_idx')],
            },
        ),
    ]
