# Generated by Django 5.2.8 on 2025-11-10 06:12

import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, validators=[core.validators.validate_phone_number], verbose_name='Phone Number')),
                ('position', models.CharField(choices=[('worker', 'Worker'), ('master', 'Master'), ('quality_controller', 'Quality Controller'), ('supervisor', 'Supervisor')], default='worker', max_length=50, verbose_name='Position')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary')], default='full_time', max_length=20, verbose_name='Employment Type')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Base hourly rate in UZS', max_digits=10, null=True, verbose_name='Hourly Rate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('hired_at', models.DateField(verbose_name='Hire Date')),
                ('terminated_at', models.DateField(blank=True, null=True, verbose_name='Termination Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='employees_user_id_93c151_idx'), models.Index(fields=['position'], name='employees_positio_4ed529_idx'), models.Index(fields=['is_active'], name='employees_is_acti_e91717_idx')],
            },
        ),
    ]
